# Generated by Django 5.1.4 on 2025-04-01 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prideuser',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
