# Generated by Django 5.1.4 on 2025-04-09 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_refresh_token_activetoken_active_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activetoken',
            old_name='active_token',
            new_name='refresh_token',
        ),
    ]
