# Generated by Django 5.1.4 on 2025-04-09 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_active_token_activetoken_refresh_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='activetoken',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
