# Generated by Django 5.1.4 on 2025-04-09 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_activetoken_enabled'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActiveToken',
        ),
    ]
