# Generated by Django 5.1.4 on 2025-04-09 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_tokenhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokenhistory',
            name='refresh_token',
            field=models.CharField(max_length=255),
        ),
    ]
