# Generated by Django 5.1.4 on 2025-04-10 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_prideuser_enabled_passwordhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='prideuser',
            name='temporary_password_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
