# Generated by Django 5.1.4 on 2025-04-10 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_prideuser_temporary_password_expiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='prideuser',
            name='password_reset_token',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='prideuser',
            name='password_reset_token_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
