# Generated by Django 5.1.4 on 2025-04-11 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_prideuser_password_reset_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prideuser',
            name='failed_login_attempts',
            field=models.IntegerField(default=0),
        ),
    ]
