# Generated by Django 5.1.4 on 2025-04-11 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_prideuser_failed_login_attempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='prideuser',
            name='is_deactivated',
            field=models.BooleanField(default=False),
        ),
    ]
