# Generated by Django 5.1.4 on 2025-01-07 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SMSLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
                ('message', models.TextField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('amount_due', models.FloatField()),
                ('status', models.CharField(max_length=50)),
                ('response_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
