# Generated by Django 5.1.4 on 2025-02-26 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pride_notify_notice', '0003_birthdayrequestsrequestdatatlogs_birthdaysmslog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BirthdayRequestsRequestDatatLogs',
        ),
        migrations.DeleteModel(
            name='RequestDatatLogs',
        ),
        migrations.RemoveField(
            model_name='birthdaysmslog',
            name='email',
        ),
        migrations.AddField(
            model_name='birthdaysmslog',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
