# Generated by Django 5.1.4 on 2025-02-26 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pride_notify_notice', '0004_delete_birthdayrequestsrequestdatatlogs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='birthdaysmslog',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
