# Generated by Django 4.1.2 on 2025-09-02 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pride_notify_notice', '0005_birthdaysmslog_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupLoanSMSLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acct_nm', models.CharField(max_length=255)),
                ('group_cust_no', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True, null=True)),
                ('contact', models.CharField(max_length=15)),
                ('response_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
