# Generated by Django 4.1.2 on 2025-09-02 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pride_notify_notice', '0006_grouploansmslog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouploansmslog',
            name='status',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
