# Generated by Django 4.1.2 on 2025-10-23 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pride_notify_notice', '0007_alter_grouploansmslog_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupSMSLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('status', models.CharField(max_length=50)),
                ('response_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
