# Generated by Django 4.1.2 on 2026-01-23 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pride_notify_notice', '0008_groupsmslog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ATMExpirySMSLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_id', models.CharField(max_length=50)),
                ('cust_no', models.CharField(max_length=50)),
                ('pan_masked', models.CharField(max_length=20)),
                ('card_title', models.CharField(max_length=255)),
                ('requested_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('transaction_acct', models.CharField(max_length=50)),
                ('mobile_contact', models.CharField(max_length=15)),
                ('message', models.TextField(blank=True, null=True)),
                ('response_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
