# Generated by Django 4.1.2 on 2026-03-31 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pride_notify_notice', '0009_atmexpirysmslog'),
    ]

    operations = [
        migrations.CreateModel(
            name='GregSchoolSMSLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acct_nm', models.CharField(max_length=255)),
                ('txn_amount', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True, null=True)),
                ('ledger', models.CharField(blank=True, max_length=255, null=True)),
                ('tran_description', models.CharField(blank=True, max_length=255, null=True)),
                ('contact', models.CharField(max_length=15)),
                ('txn_date', models.DateField(blank=True, null=True)),
                ('response_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
