# Generated by Django 5.1.4 on 2025-04-08 14:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0003_groupaudittrail'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserTrail',
            new_name='AuditTrail',
        ),
        migrations.DeleteModel(
            name='GroupAuditTrail',
        ),
    ]
